//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSaludOcupacional.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Proceso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Proceso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSaludOcupacional.Resources.Proceso", typeof(Proceso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB.
        /// </summary>
        internal static string Cambios {
            get {
                return ResourceManager.GetString("Cambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        internal static string Envases {
            get {
                return ResourceManager.GetString("Envases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIN.
        /// </summary>
        internal static string FinConteo {
            get {
                return ResourceManager.GetString("FinConteo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LQ.
        /// </summary>
        internal static string Liquido {
            get {
                return ResourceManager.GetString("Liquido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NP.
        /// </summary>
        internal static string NoPlanificados {
            get {
                return ResourceManager.GetString("NoPlanificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT.
        /// </summary>
        internal static string Otros {
            get {
                return ResourceManager.GetString("Otros", resourceCulture);
            }
        }
    }
}
